env:
  global:
    - EDK2_URL=https://github.com/tianocore/edk2.git
    - EDK2_VERSION=vUDK2018

dist: trusty

sudo: false

language: c

cache: ccache

compiler:
  - gcc

addons:
  apt:
    packages:
      - nasm
  coverity_scan:
    project:
      name: "ipxe/ProxyLoaderPkg"
      version: $TRAVIS_COMMIT
    build_command: "build -a X64 -t GCC5 -p ProxyLoaderPkg/ProxyLoaderPkg.dsc"
    branch_pattern: coverity_scan

install:
  - git clone --depth 1 --branch ${EDK2_VERSION} ${EDK2_URL}
  - cd edk2
  - . edksetup.sh
  - ln -s .. ProxyLoaderPkg
  - make -C BaseTools/Source/C

script:
  - build -a X64 -t GCC5 -p ProxyLoaderPkg/ProxyLoaderPkg.dsc
