name: Coverity Scan

on:
  push:
    branches:
      - coverity_scan

env:
  EDK2_URL: https://github.com/tianocore/edk2.git
  EDK2_VERSION: vUDK2018

jobs:

  submit:
    name: Submit
    runs-on: ubuntu-18.04
    steps:

      - name: Check out code
        uses: actions/checkout@v2


      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           nasm uuid-dev

      - name: Download Coverity Scan
        run: |
          curl --form token=${{ secrets.COVERITY_SCAN_TOKEN }} \
               --form project=${{ github.repository }} \
               --output coverity.tar.gz \
               https://scan.coverity.com/download/cxx/linux64
          mkdir -p /opt/coverity
          sudo tar xzf coverity.tar.gz --strip 1 --directory /opt/coverity

      - name: Download EDK2
        run: |
          git clone --depth 1 --branch ${EDK2_VERSION} ${EDK2_URL}
          ln -s .. edk2/ProxyLoaderPkg
          make -C edk2/BaseTools/Source/C

      - name: Build via Coverity Scan
        working-directory: edk2
        run: |
          . edksetup.sh
          /opt/coverity/bin/cov-build --dir cov-int \
              build -a X64 -t GCC5 -p ProxyLoaderPkg/ProxyLoaderPkg.dsc

      - name: Create submission
        working-directory: edk2
        run : |
          tar cvzf cov-int.tar.gz cov-int

      - name: Submit to Coverity Scan
        working-directory: edk2
        run: |
          curl --form token=${{ secrets.COVERITY_SCAN_TOKEN }} \
               --form email=${{ secrets.COVERITY_SCAN_EMAIL }} \
               --form file=@cov-int.tar.gz \
               --form version=${{ github.sha }} \
               --form description=${{ github.ref }} \
               https://scan.coverity.com/builds?project=${{ github.repository }}
